<?php

/**
 * Debug Bar screen template.
 *
 * It uses Font Awesome by Dave Gandy - http://fontawesome.io
 *
 * This file is part of the Tracy (https://tracy.nette.org)
 * Copyright (c) 2004 David Grudl (https://davidgrudl.com)
 *
 * @param  array  $panels
 * @param  array  $liveData
 * @param  string $ajaxRoute
 * @return void
 */

namespace Tracy;

use Tracy;

?>




<!-- Tracy Debug Bar -->

<?php ob_start() ?>
&nbsp;

<style id="tracy-debug-style" class="tracy-debug" type="text/css">
<?php readfile(__DIR__ . '/bar.css') ?>
<?php readfile(__DIR__ . '/../Toggle/toggle.css') ?>
<?php readfile(__DIR__ . '/../Dumper/dumper.css') ?>
</style>

<script id="tracy-debug-script" type="text/javascript">
<?php readfile(__DIR__ . '/../util.js') ?>
<?php readfile(__DIR__ . '/bar.js') ?>
<?php readfile(__DIR__ . '/../Toggle/toggle.js') ?>
<?php readfile(__DIR__ . '/../Dumper/dumper.js') ?>
</script>

<?php $output = ob_get_clean(); ?>


<script type="text/javascript">
(function() {
	if (!document.documentElement.classList) {
		document.write('<div style="position:fixed;right:0;bottom:0;z-index:30000;font:normal normal 12px/21px sans-serif;color:#333;background:#EDEAE0;border:1px solid #ccc;padding:.2em">Warning: Tracy requires IE 10+<\/div>');
		return;
	}

	window.addEventListener('load', function() {
		var debug = document.body.appendChild(document.createElement('div'));
		debug.id = 'tracy-debug';
		debug.innerHTML = <?= json_encode(Helpers::fixEncoding($output)) ?>;

		for (var i = 0, scripts = [].slice.call(debug.getElementsByTagName('script')); i < scripts.length; i++) {
			if (!scripts[i].type || scripts[i].type.toLowerCase() === 'text/javascript') {
				var load = scripts[i].hasAttribute('src'),
					src = load ? scripts[i].src : (scripts[i].text || scripts[i].textContent || scripts[i].innerHTML || ''),
					script = document.createElement('script');

				script.type = 'text/javascript';
				script.id = scripts[i].id;
				scripts[i].id = null;

				if (load) {
					script.src = src;
				} else {
					try {
						script.appendChild(document.createTextNode(src));
					} catch (e) {
						script.text = src;
					}
				}

				scripts[i].parentNode.insertBefore(script, scripts[i]);
				scripts[i].parentNode.removeChild(scripts[i]);
			}
		}
		Tracy.Dumper.init(<?= json_encode($liveData) ?>);
		Tracy.Debug.getInstance().build(<?= json_encode($sections) ?>);

		<?php if ($ajaxRoute) { ?>
		Tracy.Debug.getInstance().setAjaxRoute(<?= json_encode($ajaxRoute) ?>);
		<?php } ?>
		debug.style.display = 'block';
	});
})();
</script>

<!-- /Tracy Debug Bar -->
